#!/bin/bash
pluginName=$2
pluginType=$1

case "$pluginType" in
	'objects')
	/system/gitcloner madnerds/kana-$pluginName "/opt/piget/kana/www/plugins/objects/$pluginName"
	chmod 700 -R /opt/piget/kana/www/plugins/objects/$pluginName
	chown -R www-data:www-data /opt/piget/kana/www/plugins/objects/$pluginName
	;;
	'views')
	/system/gitcloner madnerds/kana-$pluginName "/opt/piget/kana/www/plugins/views/$pluginName"
	chmod 700 -R /opt/piget/kana/www/plugins/views/$pluginName
	chown -R www-data:www-data /opt/piget/kana/www/plugins/views/$pluginName
	;;
	'sensors')
	/system/gitcloner madnerds/kana-$pluginName "/opt/piget/kana/www/plugins/sensors/$pluginName"
	chmod 700 -R /opt/piget/kana/www/plugins/sensors/$pluginName
	chown -R www-data:www-data /opt/piget/kana/www/plugins/sensors/$pluginName
	;;
	*)
        /show/errorBox "Wrong Plugin type"
        /show/usage 'kanaAdd "pluginType" "pluginName"'
        /show/example 'kanaAdd "objects" "led"'
	;;
esac
