#!/bin/bash

objectsFile="/opt/user/config/kana/install/repo/objects.txt"
viewsFile="/opt/user/config/kana/install/repo/views.txt"
sensorsFile="/opt/user/config/kana/install/repo/sensors.txt"

if [ -e "$objectsFile" ];then
/show/description "Download Objects"
	while read repo; do
		reponame=$(echo $repo|awk -F kana- {'print $2'})
		/do/kana/addCustom $repo "objects" $reponame
	done < $objectsFile
fi

if [ -e "$viewsFile" ];then
/show/description "Download views"
        while read repo; do
                reponame=$(echo $repo|awk -F kana- {'print $2'})
                /do/kana/addCustom $repo "views" $reponame
        done < $objectsFile
fi

if [ -e "$objectsFile" ];then
/show/description "Download sensors"
        while read repo; do
                reponame=$(echo $repo|awk -F kana- {'print $2'})
                /do/kana/addCustom $repo "sensors" $reponame
        done < $objectsFile
fi

/do/kana/check
