#!/bin/bash
pluginName=$3
pluginRepo=$1
pluginType=$2

case "$pluginType" in
        'objects')
        /system/gitcloner $pluginRepo "/opt/piget/kana/www/plugins/objects/$pluginName"
        chmod 700 -R /opt/piget/kana/www/plugins/objects/$pluginName
        chown -R www-data:www-data /opt/piget/kana/www/plugins/objects/$pluginName
        ;;
        'views')
        /system/gitcloner $pluginRepo "/opt/piget/kana/www/plugins/views/$pluginName"
        chmod 700 -R /opt/piget/kana/www/plugins/views/$pluginName
        chown -R www-data:www-data /opt/piget/kana/www/plugins/views/$pluginName
        ;;
        'sensors')
        /system/gitcloner $pluginRepo "/opt/piget/kana/www/plugins/sensors/$pluginName"
        chmod 700 -R /opt/piget/kana/www/plugins/sensors/$pluginName
        chown -R www-data:www-data /opt/piget/kana/www/plugins/sensors/$pluginName
        ;;
        *)
        /show/errorBox "Wrong Plugin type"
        /show/usage 'kanaAdd "pluginRepo" "pluginType" "pluginName"'
        /show/example 'kanaAdd "madnerds/kana-led" "objects" "led"'
        ;;
esac

