#!/bin/bash
/opt/piget/core/extendPath

description "Kana is going to be install"

messagebox "Give access to configuration files with samba"
downloadModule samba
. extendPath
sambaDownload kana_dev

messagebox "Install wiringPi to manage GPIO"
wiringPiInstall

messagebox "Clone kana"
gitcloner madnerds/kana /opt/piget/kana/www

messagebox "Install nginx webserver"
downloadModule nginx
. extendPath
nginxInstall

messagebox "Use kana with nginx"
nginxDir /opt/piget/kana/www

messagebox "Install additional librairies"
nginxSqlite
nginxDebug
installer php5-mcrypt
installer php5-cgi

# Install previously installed plugins


# Check permissions
mkdir /opt/user/config/kana/objects
mkdir /opt/user/config/kana/sensors
mkdir /opt/user/data/kana
checkPermissions


